// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxgesjjnqoosuzzdrpdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4Z2VzampucW9vc3V6emRycGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxOTgyNTAsImV4cCI6MjA1Mzc3NDI1MH0.fEpBWr900yfxlZ3kIkcKgXEdlPlTEatWwViF8DNbyZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});